version: '3.7'

services:
  vuetify-app:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-vuetify
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./vuetify-project:/home/node/app
    expose:
      - 3000
    ports:
      - 3000:3000
    command: yarn dev

    

